[package]
name = "stardewvalley-mod-manager"
version = "0.1.0"
authors = ["Daniel Atwood <daniel@atwood.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
polodb_core = "0.6.0"
polodb_bson = "0.6.0"